### ISSUE TITLE
grep -P is unrecognizable

### ISSUE THREAD

**Issue by anshumanbh** [almroot/dnsresolvers#1]
Not sure what the `-P` flag is for in the grep command being used. None of the OS I tried running this script on recognizes that. Is this supposed to be `pattern`?

**Comment by almroot** [comment]
I've been using grep 3.0, and the `-P` flag states the following:

```
  -P, --perl-regexp         PATTERN is a Perl regular expression
```

It should be fine to use `-E`, or simply `egrep` too.

**Comment by anshumanbh** [comment]
Thanks!!

**Comment by almroot** [comment]
No problems!
